spring.application.name=Axon_Restate_Demo
server.port=8888

axon.serializer.general=jackson

axon.eventhandling.processors.bike-projection.mode=pooled
axon.eventhandling.processors.bike-projection.initial-segment-count=4

restate-ingress.url=http://127.0.0.1:8080